version: '3'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "6000:6000"
    working_dir: /app
    command: gunicorn app:app --bind 0.0.0.0:6000
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    working_dir: /app
    command: npm run start
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true
