name: FullStack CI/CD

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd ~/TaskFlow || (mkdir ~/app && cd ~/app && git init && git remote add origin https://github.com/kudiyarohit/TaskFlow.git)
            git pull origin master

            docker-compose down || true
            docker-compose build
            docker-compose up -d
